package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yz.books.db.AudioCategory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "audio_category".
*/
public class AudioCategoryDao extends AbstractDao<AudioCategory, Long> {

    public static final String TABLENAME = "audio_category";

    /**
     * Properties of entity AudioCategory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "categorysId");
        public final static Property CategorysName = new Property(1, String.class, "categorysName", false, "categorysName");
        public final static Property ParentId = new Property(2, int.class, "parentId", false, "parentId");
    }


    public AudioCategoryDao(DaoConfig config) {
        super(config);
    }
    
    public AudioCategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AudioCategory entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String categorysName = entity.getCategorysName();
        if (categorysName != null) {
            stmt.bindString(2, categorysName);
        }
        stmt.bindLong(3, entity.getParentId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AudioCategory entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String categorysName = entity.getCategorysName();
        if (categorysName != null) {
            stmt.bindString(2, categorysName);
        }
        stmt.bindLong(3, entity.getParentId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AudioCategory readEntity(Cursor cursor, int offset) {
        AudioCategory entity = new AudioCategory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // categorysName
            cursor.getInt(offset + 2) // parentId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AudioCategory entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCategorysName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setParentId(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AudioCategory entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AudioCategory entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AudioCategory entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
