package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yz.books.db.AudioDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "audio_detail".
*/
public class AudioDetailDao extends AbstractDao<AudioDetail, Long> {

    public static final String TABLENAME = "audio_detail";

    /**
     * Properties of entity AudioDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "audioId");
        public final static Property AudioName = new Property(1, String.class, "audioName", false, "audioName");
        public final static Property CoverImg = new Property(2, String.class, "coverImg", false, "coverImg");
        public final static Property Author = new Property(3, String.class, "author", false, "author");
        public final static Property QrCode = new Property(4, String.class, "qrCode", false, "qrCode");
        public final static Property ChapterUrl = new Property(5, String.class, "chapterUrl", false, "chapterUrl");
        public final static Property Recommend = new Property(6, String.class, "recommend", false, "recommend");
        public final static Property FirstLetters = new Property(7, String.class, "firstLetters", false, "firstLetters");
    }


    public AudioDetailDao(DaoConfig config) {
        super(config);
    }
    
    public AudioDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AudioDetail entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String audioName = entity.getAudioName();
        if (audioName != null) {
            stmt.bindString(2, audioName);
        }
 
        String coverImg = entity.getCoverImg();
        if (coverImg != null) {
            stmt.bindString(3, coverImg);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(5, qrCode);
        }
 
        String chapterUrl = entity.getChapterUrl();
        if (chapterUrl != null) {
            stmt.bindString(6, chapterUrl);
        }
 
        String recommend = entity.getRecommend();
        if (recommend != null) {
            stmt.bindString(7, recommend);
        }
 
        String firstLetters = entity.getFirstLetters();
        if (firstLetters != null) {
            stmt.bindString(8, firstLetters);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AudioDetail entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String audioName = entity.getAudioName();
        if (audioName != null) {
            stmt.bindString(2, audioName);
        }
 
        String coverImg = entity.getCoverImg();
        if (coverImg != null) {
            stmt.bindString(3, coverImg);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(5, qrCode);
        }
 
        String chapterUrl = entity.getChapterUrl();
        if (chapterUrl != null) {
            stmt.bindString(6, chapterUrl);
        }
 
        String recommend = entity.getRecommend();
        if (recommend != null) {
            stmt.bindString(7, recommend);
        }
 
        String firstLetters = entity.getFirstLetters();
        if (firstLetters != null) {
            stmt.bindString(8, firstLetters);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AudioDetail readEntity(Cursor cursor, int offset) {
        AudioDetail entity = new AudioDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // audioName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // coverImg
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // author
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // qrCode
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // chapterUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // recommend
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // firstLetters
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AudioDetail entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAudioName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCoverImg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAuthor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setQrCode(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setChapterUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRecommend(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFirstLetters(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AudioDetail entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AudioDetail entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AudioDetail entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
