package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yz.books.db.JournalDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "journal_details".
*/
public class JournalDetailDao extends AbstractDao<JournalDetail, Long> {

    public static final String TABLENAME = "journal_details";

    /**
     * Properties of entity JournalDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "journalId");
        public final static Property JournalName = new Property(1, String.class, "journalName", false, "journalName");
        public final static Property CoverImg = new Property(2, String.class, "coverImg", false, "coverImg");
        public final static Property Author = new Property(3, String.class, "author", false, "author");
        public final static Property BookType = new Property(4, String.class, "bookType", false, "bookType");
        public final static Property Path = new Property(5, String.class, "path", false, "path");
        public final static Property FileMd5String = new Property(6, String.class, "fileMd5String", false, "fileMd5String");
        public final static Property QrCode = new Property(7, String.class, "qrCode", false, "qrCode");
        public final static Property IsCollect = new Property(8, Integer.class, "isCollect", false, "isCollect");
        public final static Property Recommend = new Property(9, String.class, "recommend", false, "recommend");
        public final static Property Content = new Property(10, String.class, "content", false, "content");
        public final static Property FirstLetters = new Property(11, String.class, "firstLetters", false, "firstLetters");
        public final static Property LateralReader = new Property(12, String.class, "lateralReader", false, "lateralReader");
    }


    public JournalDetailDao(DaoConfig config) {
        super(config);
    }
    
    public JournalDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JournalDetail entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String journalName = entity.getJournalName();
        if (journalName != null) {
            stmt.bindString(2, journalName);
        }
 
        String coverImg = entity.getCoverImg();
        if (coverImg != null) {
            stmt.bindString(3, coverImg);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String bookType = entity.getBookType();
        if (bookType != null) {
            stmt.bindString(5, bookType);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(6, path);
        }
 
        String fileMd5String = entity.getFileMd5String();
        if (fileMd5String != null) {
            stmt.bindString(7, fileMd5String);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(8, qrCode);
        }
 
        Integer isCollect = entity.getIsCollect();
        if (isCollect != null) {
            stmt.bindLong(9, isCollect);
        }
 
        String recommend = entity.getRecommend();
        if (recommend != null) {
            stmt.bindString(10, recommend);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(11, content);
        }
 
        String firstLetters = entity.getFirstLetters();
        if (firstLetters != null) {
            stmt.bindString(12, firstLetters);
        }
 
        String lateralReader = entity.getLateralReader();
        if (lateralReader != null) {
            stmt.bindString(13, lateralReader);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JournalDetail entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String journalName = entity.getJournalName();
        if (journalName != null) {
            stmt.bindString(2, journalName);
        }
 
        String coverImg = entity.getCoverImg();
        if (coverImg != null) {
            stmt.bindString(3, coverImg);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String bookType = entity.getBookType();
        if (bookType != null) {
            stmt.bindString(5, bookType);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(6, path);
        }
 
        String fileMd5String = entity.getFileMd5String();
        if (fileMd5String != null) {
            stmt.bindString(7, fileMd5String);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(8, qrCode);
        }
 
        Integer isCollect = entity.getIsCollect();
        if (isCollect != null) {
            stmt.bindLong(9, isCollect);
        }
 
        String recommend = entity.getRecommend();
        if (recommend != null) {
            stmt.bindString(10, recommend);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(11, content);
        }
 
        String firstLetters = entity.getFirstLetters();
        if (firstLetters != null) {
            stmt.bindString(12, firstLetters);
        }
 
        String lateralReader = entity.getLateralReader();
        if (lateralReader != null) {
            stmt.bindString(13, lateralReader);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JournalDetail readEntity(Cursor cursor, int offset) {
        JournalDetail entity = new JournalDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // journalName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // coverImg
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // author
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bookType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // path
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fileMd5String
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // qrCode
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // isCollect
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // recommend
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // content
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // firstLetters
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // lateralReader
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JournalDetail entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJournalName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCoverImg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAuthor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBookType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPath(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFileMd5String(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setQrCode(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsCollect(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setRecommend(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setContent(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFirstLetters(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setLateralReader(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JournalDetail entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JournalDetail entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JournalDetail entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
