package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yz.books.db.Video;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Video".
*/
public class VideoDao extends AbstractDao<Video, Long> {

    public static final String TABLENAME = "Video";

    /**
     * Properties of entity Video.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "videoId");
        public final static Property VideoName = new Property(1, String.class, "videoName", false, "videoName");
        public final static Property CoverImg = new Property(2, String.class, "coverImg", false, "coverImg");
        public final static Property Description = new Property(3, String.class, "description", false, "description");
        public final static Property Author = new Property(4, String.class, "author", false, "author");
        public final static Property QrCode = new Property(5, String.class, "qrCode", false, "qrCode");
        public final static Property CategoryId = new Property(6, int.class, "categoryId", false, "categoryId");
        public final static Property FirstLetters = new Property(7, String.class, "firstLetters", false, "firstLetters");
    }


    public VideoDao(DaoConfig config) {
        super(config);
    }
    
    public VideoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Video entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String videoName = entity.getVideoName();
        if (videoName != null) {
            stmt.bindString(2, videoName);
        }
 
        String coverImg = entity.getCoverImg();
        if (coverImg != null) {
            stmt.bindString(3, coverImg);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(5, author);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(6, qrCode);
        }
        stmt.bindLong(7, entity.getCategoryId());
 
        String firstLetters = entity.getFirstLetters();
        if (firstLetters != null) {
            stmt.bindString(8, firstLetters);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Video entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String videoName = entity.getVideoName();
        if (videoName != null) {
            stmt.bindString(2, videoName);
        }
 
        String coverImg = entity.getCoverImg();
        if (coverImg != null) {
            stmt.bindString(3, coverImg);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(4, description);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(5, author);
        }
 
        String qrCode = entity.getQrCode();
        if (qrCode != null) {
            stmt.bindString(6, qrCode);
        }
        stmt.bindLong(7, entity.getCategoryId());
 
        String firstLetters = entity.getFirstLetters();
        if (firstLetters != null) {
            stmt.bindString(8, firstLetters);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Video readEntity(Cursor cursor, int offset) {
        Video entity = new Video( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // videoName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // coverImg
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // author
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // qrCode
            cursor.getInt(offset + 6), // categoryId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // firstLetters
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Video entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVideoName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCoverImg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAuthor(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setQrCode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCategoryId(cursor.getInt(offset + 6));
        entity.setFirstLetters(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Video entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Video entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Video entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
